### ISSUE TITLE
Parameters with same name as a step_data cause very difficult to debug problems

### ISSUE THREAD

**Issue by dcharbon** [Quansight/llstep#4]
We ran into this with a `step_data` declared with the name `config` while there was also a function parameter named `config`. In this case, the function parameter was an instance of a `dict` subclass. The result was an error stating that `config` was an instance of `Configuration` and was unhashable. The reason this was the error was due to the rewriting of `config` to `context[config]` by the `StepBodyRewriter`.

The `StepBodyRewriter` should respect the override of the `step_data` imported name and not rewrite that reference in that case. Further, it should log to `INFO` that it's skipping that name to aid with future debugging.

**Comment by dillonroach** [comment]
tentatively finished, just waiting for a quick live-session to verify I'm fulfilling the brief and then I'll set up a branch

**Comment by dillonroach** [comment]
a pull request has submitted, if accepted I'll go ahead and close this.
